# Generated by Django 5.1.3 on 2025-01-31 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('pizza_type', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
